//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econmed.ImageViewer.Layout.HangingProtocols {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Econmed.ImageViewer.Layout.HangingProtocols.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Sets or Study.
        /// </summary>
        internal static string MenuNextDisplaySets {
            get {
                return ResourceManager.GetString("MenuNextDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Sets or Study.
        /// </summary>
        internal static string MenuPreviousDisplaySets {
            get {
                return ResourceManager.GetString("MenuPreviousDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of given image-box elements ({0}) does not match rows ({1}) * columns ({2}) within workspace &apos;{3}&apos;..
        /// </summary>
        internal static string MessageAmountOfImageBoxesMismatch {
            get {
                return ResourceManager.GetString("MessageAmountOfImageBoxesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading hanging protocols from settings..
        /// </summary>
        internal static string MessageErrorWhileLoadingHangingProtocols {
            get {
                return ResourceManager.GetString("MessageErrorWhileLoadingHangingProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DisplaySet that matches the filter &apos;{0}&apos; had been found
        ///in ImageSet &apos;{1}&apos;
        ///for Workspace &apos;{2}&apos;..
        /// </summary>
        internal static string MessageNoMatchingDisplaySet {
            get {
                return ResourceManager.GetString("MessageNoMatchingDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching hanging protocol was found for &apos;{0} | {1}&apos;..
        /// </summary>
        internal static string MessageNoMatchingHangingProtocol {
            get {
                return ResourceManager.GetString("MessageNoMatchingHangingProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Sets or Study.
        /// </summary>
        internal static string ToolbarNextDisplaySets {
            get {
                return ResourceManager.GetString("ToolbarNextDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Sets or Study.
        /// </summary>
        internal static string ToolbarPreviousDisplaySets {
            get {
                return ResourceManager.GetString("ToolbarPreviousDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Sets or Study.
        /// </summary>
        internal static string TooltipNextDisplaySets {
            get {
                return ResourceManager.GetString("TooltipNextDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Sets or Study.
        /// </summary>
        internal static string TooltipPreviousDisplaySets {
            get {
                return ResourceManager.GetString("TooltipPreviousDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unnamed.
        /// </summary>
        internal static string WorkspaceDefaultName {
            get {
                return ResourceManager.GetString("WorkspaceDefaultName", resourceCulture);
            }
        }
    }
}
